name: prompts.chat
title: prompts.chat
subtitle: World's First & Most Famous Prompts Directory

url: "https://prompts.chat"

github_pages:
  url: "https://prompts.chat"
  branch: "main"

plugins:
  - jekyll-seo-tag

exclude:
  - vendor
  - node_modules
  - scripts
  - Gemfile
  - Gemfile.lock
  - README.md
  - REPO_REFERENCES.md
  - SESSION_LOG.md
  - .github
